[Broadcaster] Add headless client

diff --git a/.github/workflows/__CD__broadcaster.yml b/.github/workflows/__CD__broadcaster.yml
--- a/.github/workflows/__CD__broadcaster.yml
+++ b/.github/workflows/__CD__broadcaster.yml
@@ -27,11 +27,18 @@ jobs:
           username: ${{ secrets.BROADCASTER_SSH_USERNAME }}
           key: ${{ secrets.BROADCASTER_SSH_PRIV_KEY }}
           script: |
+            # Exit if any command fails.
+            set -e
+
             export APP_NAME=broadcaster
             export TAG=${{ github.ref_name }}
             export TAG=${TAG#*-v}
+
+            echo "Cleaning previous broadcaster docker image"
             docker stop $APP_NAME
             docker rm $APP_NAME
+
+            echo "Running a new broadcaster image - $TAG"
             docker run -d --restart unless-stopped \
               --name $APP_NAME \
               -e SECRET_KEY_BASE=${{ secrets.BROADCASTER_SECRET_KEY_BASE }} \
@@ -42,10 +49,40 @@ jobs:
               -e WHIP_TOKEN=${{ secrets.BROADCASTER_WHIP_TOKEN }} \
               --network host \
               ghcr.io/elixir-webrtc/apps/$APP_NAME:$TAG
+
             docker image prune --all --force
 
+            echo "Waiting for broadcaster to be ready."
+            attempts=10
+            until curl localhost:4000 > /dev/null 2>&1
+            do 
+              ((attempts--))
+              if [ $attempts -eq 0 ]; then
+                exit 1
+              fi
+              sleep 1
+            done
+            
+            echo "Cloning client script"
+            rm -rf /tmp/apps
+            git clone -b ${{ github.ref_name }} https://github.com/${{ github.repository }} /tmp/apps
+            cd /tmp/apps/broadcaster
 
+            echo "Terminating previously running client"
+            # ignore non-zero exit status
+            killall node || true
+            
+            # This is needed to find `node` and `npm` commands.
+            # See difference between interactive and non-interactive shells.
+            source ~/.nvm/nvm.sh
+            
+            echo "Installing puppeteer in current directory"
+            npm install puppeteer
 
-
-
-
+            # Run node in bg, disconnect it from terminal and redirect all output. 
+            # In other case action won't end.
+            echo "Running client script"
+            USERNAME=${{ secrets.BROADCASTER_ADMIN_USERNAME }} \
+              PASSWORD=${{ secrets.BROADCASTER_ADMIN_PASSWORD }} \
+              TOKEN=${{ secrets.BROADCASTER_WHIP_TOKEN }} \
+              nohup node headless_client.js > nohup.out 2> nohup.err < /dev/null &
